name: dev-drupal-security
recipe: lamp
config:
  database: mysql:5.7.40
services:
  appserver:
    type: php:8.1
    xdebug: debug
    config:
      php: scripts/lando-customizations/php.ini
    webroot: .
