name: dev-drupal-security
proxy:
  appserver:
    - dev-drupal-security.lndo.site
services:
  appserver:
    ssl: true
    type: 'php:8.1'
    via: apache
    xdebug: debug
    config:
      php: scripts/lando-customizations/php.ini
    webroot: .
tooling:
  composer:
    service: appserver
    cmd: composer --ansi
  php:
    service: appserver
    cmd: php
